services:
  go-course-user:
    platform: linux/amd64
    container_name: go-course-user
    build:
      context: ./.docker/mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=go_course_user
    ports:
      - "3321:3306"
    volumes:
      - ./.docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql